const { GoogleGenAI } = require("@google/genai");
const { z } = require("zod");
const { zodToJsonSchema } = require("zod-to-json-schema");
const puppeteer = require("puppeteer");

const ai = new GoogleGenAI({
  apiKey: process.env.GOOGLE_GENAI_API_KEY,
});

async function invokeGeminiAI() {
  const response = await ai.models.generateContent({
    model: "gemini-3.5-flash",
    contents: "Explain how AI works in a few words",
  });

  console.log(response.text);
}

const interviewReportSchema = z.object({
  matchScore: z.number().describe("A score representing how well the user's profile matches the job description"),
  technicalQuestions: z.array(z.object({
    question: z.string().describe("The technical interview question"),
    intention: z.string().describe("The intention behind the question"),
    answer: z.string().describe("The user's answer to the question")
  })).describe("A list of technical interview questions, their intentions, and the user's answers"),
  behavioralQuestions: z.array(z.object({
    question: z.string().describe("The behavioral interview question"),
    intention: z.string().describe("The intention behind the question"),
    answer: z.string().describe("The user's answer to the question")
  })).describe("A list of behavioral interview questions, their intentions, and the user's answers"),
  skillGaps: z.array(z.object({
    skill: z.string().describe("The skill that is lacking"),
    severity: z.enum(["low", "medium", "high"]).describe("The severity of the skill gap")
  })).describe("A list of identified skill gaps"),
  preparationPlan: z.array(z.object({
    day: z.number().describe("The day number in the preparation plan"),
    focus: z.string().describe("The focus area for that day"),
    tasks: z.array(z.string()).describe("A list of tasks to complete on that day")
  })).describe("A structured preparation plan with daily focus areas and tasks"),
  title: z.string().describe("The titlte of the job being applied for"),
});

async function generateInterviewReport({ resume, selfDescription, jobDescription }) {
  const prompt = `Generate an interview preparation report based on the following information in the given format structure:

  Resume: ${resume}
  Self Description: ${selfDescription}
  Job Description: ${jobDescription}
  `

  const response = await ai.models.generateContent({
    model: "gemini-3.1-flash-lite",
    contents: prompt,
    config: {
      responseMimeType: "application/json",
      responseJsonSchema: z.toJSONSchema(interviewReportSchema),
    },
  });

  return JSON.parse(response.text);
}

async function generateResumePdf({ resume, selfDescription, jobDescription }) {
  const resumePdfSchema = z.object({
    html: z.string().describe("The HTML content of the resume to be converted to PDF using Puppeteer")
  });

  const prompt = `Generate a PDF resume based on the following information in the given format structure:

  Resume Details: ${resume}
  Self Description: ${selfDescription}
  Job Description: ${jobDescription}

  The output should be a JSON object with an "html" field containing the HTML content of the resume. The HTML should be well-structured and formatted for conversion to PDF using Puppeteer.
  The resume should be tailored to highlight the user's strengths and relevant experience based on the job description and self-description provided. Use a clean and professional layout suitable for a wide range of industries.
  The content of resume should not sound like it was generated by AI, but rather like a resume written by a human, with natural language and appropriate formatting. Avoid including any AI-specific phrases or structures in the resume content.
  The content should be ATS friendly, ensuring that it can be easily parsed by Applicant Tracking Systems while still being visually appealing when converted to PDF.
  `
  const response = await ai.models.generateContent({
    model: "gemini-3.1-flash-lite",
    contents: prompt,
    config: {
      responseMimeType: "application/json",
      responseJsonSchema: z.toJSONSchema(resumePdfSchema),
    },
  });

  const resumeData = JSON.parse(response.text);

  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.setContent(resumeData.html, { waitUntil: "networkidle0" });
  
  const pdf = await page.pdf({ format: "A4", 
    margin: { top: "10mm", right: "10mm", bottom: "10mm", left: "10mm" }
   });

  await browser.close();

  return pdf;
}

module.exports = { invokeGeminiAI, generateInterviewReport, generateResumePdf };